name: Bug 报告
description: 创建 Bug 报告以帮助开发者改进
title: "以简单的一段字概括你所遇到的问题"
body:
  - type: markdown
    attributes:
      value: |
        ## 反馈须知
        - 请务必完整填写下面的内容，如果缺少必要的信息，将无法解决任何问题
        - 一个 issue 请只反馈一个 bug 或功能建议，一次性反馈多个不同的问题或建议或将会被直接关闭
        - 注意你的标题，以简单的一段字概括你所遇到的问题。不要使用无意义内容或全部复制粘贴
        - 该项目不为任何旧版本提供维护支持，请务必确认已更新到最新版本
        - 应用仅支持系统硬件解码，如遇到播放卡顿或无法播放，请先检查设备芯片性能以及编码支持情况

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Bug 描述
      description: 请简短地描述你遇到的问题
  - type: textarea
    id: steps
    validations:
      required: true
    attributes:
      label: 复现问题的步骤
      render: plain text
      description: 请提供复现问题的步骤，如果不能，请写明原因
      placeholder: |
        示例步骤:
        1. 进入 '...'
        2. 点击 '....'
        3. 滚动到 '....'
        4. 出现问题
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: 预期行为
      description: 简要描述你希望看到什么样的结果
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 如果可以，提交截图更有助于我们分析问题
  - type: checkboxes
    id: app-version-confirm-use-latest
    validations:
      required: true
    attributes:
      label: 该项目不确认已更新到以下所示的最新版本
      description: |
        ![App Center Release](https://img.shields.io/endpoint?url=https%3A%2F%2Fbadge.versions.bv.aaa1115910.dev%2F%3Ftype%3Drelease)
        ![App Center Alpha](https://img.shields.io/endpoint?url=https%3A%2F%2Fbadge.versions.bv.aaa1115910.dev%2F%3Ftype%3Dalpha)
      options:
        - label: 我已更新到最新版本
          required: true
  - type: input
    id: app-version
    validations:
      required: true
    attributes:
      label: 当前版本号
      placeholder: 0.0.1.r29.a6d7ecb.release (或使用缩写例如 r29)
  - type: input
    id: android-version
    validations:
      required: true
    attributes:
      label: Android 版本
      placeholder: Android 13
  - type: input
    id: device-info
    attributes:
      label: 设备厂商及型号
      placeholder: Sony - BRAVIA XR MASTER SERIES Z9K
  - type: input
    id: video
    attributes:
      label: 遇到问题的视频 avid 或 bvid
      placeholder: av170001
  - type: textarea
    id: additional-logs
    attributes:
      label: 相关日志
      description: |
        你可以在 `设置` > `更多设置` > `查看日志` 中查看已保存的日志，扫码即可下载获取（在同一网络环境下）
        在日志列表中可找到自动生成的崩溃日志，或可在功能遇到问题（例如加载失败）后手动创建日志文件
        上传文件时请务必等待文件上传完成后再提交 issue
  - type: textarea
    id: additional-content
    attributes:
      label: 附加信息
      description: 添加你认为有必要的信息，例如出现问题的相关视频等等
