name: 功能需求
description: 为项目提供建议
title: "以简单的一段字概括你的建议"
body:
  - type: markdown
    attributes:
      value: |
        ## 反馈须知
        - 请务必完整填写下面的内容，如果缺少必要的信息，将无法解决任何问题
        - 一个 issue 请只反馈一个 bug 或功能建议，一次性反馈多个不同的问题或建议或将会被直接关闭
        - 注意你的标题，以简单的一段字概括你所遇到的问题。不要使用无意义内容或全部复制粘贴
        - 提出建议也不一定会做，这不可能是万能的许愿机，如果自己确实想要，建议 fork 项目自己实现
        - 该项目不为任何旧版本提供维护支持，请务必确认已更新到最新版本

  - type: textarea
    id: problem-description
    validations:
      required: true
    attributes:
      label: 问题描述
      description: 描述你想要解决的问题或者功能的使用场景
      placeholder: 请描述你遇到的问题或者链接到已存在的 issue
  - type: textarea
    id: solution-description
    validations:
      required: true
    attributes:
      label: 描述解决方案
      description: 清晰简明地描述你所想要发生的事情，即解决方案
  - type: textarea
    id: alternatives
    attributes:
      label: 描述备选方案
      description: 解决该问题的备选方案
  - type: textarea
    id: additional-info
    attributes:
      label: 附加信息
      description: 添加你认为有必要的信息
